from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent

EXTRACTOR_ROOT = PROJECT_ROOT / "Extractor"
EXTRACTOR_CORE_ROOT = EXTRACTOR_ROOT / "core"
EXTRACTOR_INPUT_ROOT = EXTRACTOR_ROOT / "input"
EXTRACTOR_OUTPUT_ROOT = EXTRACTOR_ROOT / "output"
EXTRACTOR_CONFIG_ROOT = EXTRACTOR_ROOT / "config"
EXTRACTOR_LEGACY_ROOT = EXTRACTOR_ROOT / "legacy"
EXTRACTOR_RUNTIME_ROOT = EXTRACTOR_CORE_ROOT
EXTRACTOR_REPORT_ROOT = EXTRACTOR_INPUT_ROOT / "reports"
EXTRACTOR_CONFIG_FILE = EXTRACTOR_CONFIG_ROOT / "config.yaml"
EXTRACTOR_ENV_FILE = EXTRACTOR_CONFIG_ROOT / ".env"

EXPLAINER_ROOT = PROJECT_ROOT / "Explainer"
EXPLAINER_CORE_ROOT = EXPLAINER_ROOT / "core"
EXPLAINER_INPUT_ROOT = EXPLAINER_ROOT / "input"
EXPLAINER_OUTPUT_ROOT = EXPLAINER_ROOT / "output"
EXPLAINER_CONFIG_ROOT = EXPLAINER_ROOT / "config"
EXPLAINER_LEGACY_ROOT = EXPLAINER_ROOT / "legacy"

TRACER_ROOT = PROJECT_ROOT / "Tracer"
TRACER_CORE_ROOT = TRACER_ROOT / "core"
TRACER_INPUT_ROOT = TRACER_ROOT / "input"
TRACER_OUTPUT_ROOT = TRACER_ROOT / "output"
TRACER_CONFIG_ROOT = TRACER_ROOT / "config"
TRACER_LEGACY_ROOT = TRACER_ROOT / "legacy"
TRACER_DATA_ROOT = TRACER_OUTPUT_ROOT / "RiskTagger_Data"
TRACER_REFERENCE_ROOT = TRACER_INPUT_ROOT / "reference_list"
BLOCKCHAIN_SPIDER_ROOT = TRACER_LEGACY_ROOT / "BlockchainSpider-master"

# Backward-compatible aliases for scripts that still use the original system name.
RISKTAGGER_ROOT = TRACER_ROOT
RISKTAGGER_DATA_ROOT = TRACER_DATA_ROOT
RISKTAGGER_REFERENCE_ROOT = TRACER_REFERENCE_ROOT
